### ISSUE TITLE
How do we use this?

### ISSUE THREAD

**Issue by molecules** [SchlossLab/Zackular_AbAOMDSS_SciReports_2015#1]
Do you have installation instructions? I cloned this repository, ran "make" from the repository directory,  and got a ton of errors. 

Or alternately, is there a place that we could download the ".biom" file for this paper?

Thanks for all of your hard work on this. This was obviously a lot of work. I simply don't know how to make use of it without some additional instructions.

Here are samples of the errors:

```
cp: cannot stat `/mnt/EXT/Schloss-data/zackular/WT-Nod1-analyses/Allabs-m7247-d21_S219_L001_R1_001.fastq': No such file or directory`
...
Unable to open /share/ircf/ircfapps/bin/WTmice-m6558-d69_S21_L001_R1_001.fastq. Trying output directory data/process/WTmice-m6558-d69_S21_L001_R1_001.fastq
...
Unable to open /path/redacted/bin/VancStrep-m7253-dneg8_S265_L001_R2_001.fastq. Trying output directory data/process/VancStrep-m7253-dneg8_S265_L001_R2_001.fastq
[WARNING]: can't find data/process/VancStrep-m7253-dneg8_S265_L001_R2_001.fastq, ignoring pair.
[ERROR]: unable to spawn the number of processes you requested, reducing number to 959
/bin/sh: line 1: 11660 Segmentation fault      mothur code/get_good_seqs.batch
rm: cannot remove `data/process/*.map': No such file or directory
make: *** [data/process/ab_aomdss.trim.contigs.good.unique.good.filter.unique.precluster.denovo.uchime.pick.pick.count_table] Error 1
```

**Comment by marcsze** [comment]
I think one of the problems stems from what is in the `get_fastqs.sh` script.  In that the variable `ORIG_LOCATION` has a directory stored that I am guessing you do not have on your computer.  That is the `/mnt/EXT/Schloss-data/zackular/WT-Nod1-analyses` directory to be more specific.

The other errors might all be related to this original first one since it is looking for the fastq sequences in this directory.

I wasn't involved with the study so perhaps @pschloss can direct you to where to get the raw sequences from a public repo.  Once you have that you should be able to work through the repo analysis pipeline.

**Comment by pschloss** [comment]
The shared and taxonomy files are now in https://github.com/SchlossLab/Zackular_AbAOMDSS_mSphere_2015/tree/master/data/process.

The raw data can be obtained at the Sequence Read Archive at NCBI (Accession SRP056144) and inserted for the files that @marcsze mentioned.

If you run `make write.paper` you *should* get a compiled version of the paper. You would need mothur and R installed in your path

**Comment by molecules** [comment]
Closing this as having aged out. Sorry, I don't remember what I did in the end, but that was over five years ago.
